<?php
//@codingStandardsIgnoreFile
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>
<div class="footer-top-wrapper">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/amex.svg')?>" alt="American Express">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/discover.svg')?>" alt="Discover">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/diners.svg')?>" alt="Diners">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/jcb.svg')?>" alt="JCB">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/mastercard.svg')?>" alt="Mastercard">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('StripeIntegration_Payments::img/cards/visa.svg')?>" alt="Visa">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('Gw_Misc::img/Apple_Pay_Mark_RGB_041619.svg')?>" alt="Apple Pay">
    <img class="icon" width="53" height="35" src="<?= $block->getViewFileUrl('Gw_Misc::img/google-pay-mark_800_gray.svg')?>" alt="Google Pay">
</div>
