<?php
//@codingStandardsIgnoreFile
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>
<div class="footer-bottom-wrapper">
    <ul>
        <li>Copyright &copy; <span data-mage-init='{"Gw_Footer/js/copyright":{}}'>2024</span> Lube Finder</li>
        <li><a href="<?= $block->getBaseUrl()?>terms-and-conditions.html">Terms & Conditions</a></li>
        <li><a href="<?= $block->getBaseUrl()?>terms-and-conditions.html#privacy">Privacy</a></li>
        <li><a href="<?= $block->getBaseUrl()?>terms-and-conditions.html#returns">Returns</a></li>
        <li><a href="<?= $block->getBaseUrl()?>cookie-settings">Cookie Settings</a></li>
        <li>VAT Reg No. GB 357 0478 82</li>
    </ul>
</div>
